### ISSUE TITLE
All integer types encode/decode as int32

### ISSUE THREAD

**Issue by okkero** [andreasewering/protoc-gen-elm#139]
It seems like no matter what integer type I specify in my protofiles, the generated code will always try to encode/decode values as if they had the type `int32`. This is problematic, as decoding/encoding might end up yielding the wrong result. This seems to be especially true for `sint32` (which is how I stumbled upon this).

This seems like an oversight, as the readme implies that using all 32-bit integer types should be supported, and elm-protocol-buffers does have encoders and decoders defined for all 32-bit integer types.

At a first glance, it seems like a simple fix would be to change the implementations of `Generator.Message.toDecoder` and `Generator.Message.toEncoder` to use a decoder directly based on the field's literal data type in the protofiles, instead of its inferred Elm primitive type. See line [222](https://github.com/andreasewering/protoc-gen-elm/blob/master/src/Generator/Message.elm#L222). It seems like this branch could just be replaced with the following:
```elm
( _, Primitive _ dataType _ ) ->
    C.fqFun Meta.Decode.moduleName dataType
```
and then similar changes for lines [294](https://github.com/andreasewering/protoc-gen-elm/blob/master/src/Generator/Message.elm#L294), [328](https://github.com/andreasewering/protoc-gen-elm/blob/master/src/Generator/Message.elm#L328), [341](https://github.com/andreasewering/protoc-gen-elm/blob/master/src/Generator/Message.elm#L341) and [350](https://github.com/andreasewering/protoc-gen-elm/blob/master/src/Generator/Message.elm#L350).

I have tested these changes locally, and it does seem to work, but there may be corner cases I don't know about. If you think this seems like a feasible solution, I'll gladly submit a pull request.

**Comment by okkero** [comment]
Hello again. Any chance we can get this fixed? Thank you.

**Comment by andreasewering** [comment]
Hi okkero,
thanks for the issue.
That's a very good point. I've not run into this yet, because I only serialized/deserialized int32 values for my own project, but as you suggested, it should be quite easy to fix.

I should be able to release a new version with the fix in about a week.

**Comment by okkero** [comment]
Thank you for taking the time 👍

**Comment by andreasewering** [comment]
I invested some time to write a roundtrip test using protobufjs as a reference implementation.
As expected, encoding a message with sint32/uint32 etc. with protobufjs and then de/encoding the bytes with Elm changed the content or led to a failed decoding operation.

Using the correct methods in the generated code fixed the test and hopefully also this issue. Let me know if it works for you.

Side note - there are no methods for int64 and related types in elm-protocol-buffers, so currently you cannot use these in your proto files and expect the code to work. I'll look into the Elm Int64 package and might open a pull request to add these methods to elm-protocol-buffers (and then here as well)

**Comment by okkero** [comment]
Hi. Seems to work great. Thank you so much.

About 64-bit integers: I just surrendered early on to the fact that they're not supported. Then again, I haven't really had a case where I really needed 64-bit. Yet. I definitely see it as a worthwhile effort to add support for it, though.
