### ISSUE TITLE
Support for Int64 Datatypes

### ISSUE THREAD

**Issue by andreasewering** [andreasewering/protoc-gen-elm#148]
Currently Int64 (and its variants) are not supported and generate Int32 encoders and decoders instead.
This is obviously not compatable with servers in other languages that use these data types.

I opened a PR in elm-protocol-buffers https://github.com/eriktim/elm-protocol-buffers/pull/9 which adds encoders and decoders
for the Int64 and UInt64 data types (defined in non-official libraries).

The PR will probably change to handwritten implementations instead, but this code generator could generate the conversions to the library datatypes automatically. The downside would be additional dependencies you would need to add to your codebase.

The easiest way (and what I will probably do) to implement this would be to just use the elm-protocol-buffers representation (with no utility functions on it).
If you have an opinion on this, feel free to comment.

**Comment by andreasewering** [comment]
My PR in elm-protocol-buffers got accepted so I   released a new version that supports Int64 data types

**Comment by okkero** [comment]
I'm late to the party, but thank you for your effort on this. This will be useful for me as well :)
